### ISSUE TITLE
Nudge work in the CSD Configuration tool but not in VPX

### ISSUE THREAD

**Issue by matgenois** [philipellisis/arduino-virtual-pinball-board#10]
Hi!
So I have my own pinone board build on the schematic and the readme file of this project. I'm using the feature/new-game-controller branch. I loaded the CSD Config tool and enabled the accelerometer and calibrated it. It works fine. However, the nudge won't work in VPX. I have configured VPX to use the buttons (no keyboard mapping) and this work. 
I had this issue where Windows see 3 Arduino micro connected to it and I had to select the good one (randomly) in the advanced pane : 
![image](https://github.com/philipellisis/arduino-virtual-pinball-board/assets/7738711/4ab1ea97-fbf8-4997-9ae1-b9b4c0af6ce2)
![image](https://github.com/philipellisis/arduino-virtual-pinball-board/assets/7738711/2704c606-9290-484f-88fc-341c856d2d02)

I looked at the documentation on your website on how to config VPX for the nudge and did the same.
What i'm missing?
Is there a way to have only one controller in Windows? I'm guessing it may be related.

Thank you.

**Comment by philipellisis** [comment]
Yes, this is related to the HID library. You can fix by removing the 3 extra gamepads that are created by the library (small modification to the source here: https://github.com/NicoHood/HID/blob/master/src/SingleReport/SingleGamepad.cpp) You can read more about it here: https://github.com/NicoHood/HID/issues/266

**Comment by matgenois** [comment]
I did the change and now I only have one controller in Windows. In Windows, when I go to "Set up USB Game Controllers", I see the X/Y axis moving when I nudge but still doesn't work in VPX. Any suggestion on what I do wrong? 
![image](https://github.com/philipellisis/arduino-virtual-pinball-board/assets/7738711/47bf6cc1-cbd3-48c5-a8a7-53baafae24e5)

**Comment by philipellisis** [comment]
Your gain and max settings look wrong, recommended settings can be found here: https://pinball-docs.clevelandsoftwaredesign.com/docs/PinOne/vpx-calibration

**Comment by matgenois** [comment]
Thank you! It now works!! a little bit too much but i'll find the right settings from there I guess.

**Comment by lamarqueb** [comment]
hi goord job i cannot find the schématic ?
