### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by SJoWie80** [philipellisis/arduino-virtual-pinball-board#8]
Hi there.

i like to build this. is there any schematic on how to connect the MPU-6050, PCA9685 & 74HC165?

Thanks! 
Joey

**Comment by SJoWie80** [comment]
i have tried to make a fritzing schematic (first time) can someone look and see if my connections are right? also i cant seem to find where the three shift registers need to connect to.

![pinone](https://github.com/philipellisis/arduino-virtual-pinball-board/assets/4934607/ffee137a-5e32-429d-85fc-629557c13baf)

**Comment by philipellisis** [comment]
This is pretty close, the SDA/SDL lines are pretty simple so you have those setup right. The shift register connect as follows: SHIFT/LOAD -> PD4, CLOCK and CLOCK INHIBIT -> PD3, QH -> PD2.

There is a pretty good schematic you can follow here that will show you how to connect the button side: https://playground.arduino.cc/Code/ShiftRegSN74HC165N/

**Comment by SJoWie80** [comment]
Thank you for your reply.

i managed to get the buttons and mpu working and the first 15 outputs. howver the pca9685 seems to be reversed:
On is Off / Off is On

**Comment by philipellisis** [comment]
Yes, PCA9685 is set to sync current, so you will run 5v to the leds or
other outputs and the negative side goes to the PCA9685.

**Comment by CrazyCoder** [comment]
FYI, I found a pre-made PCB with connectors that may be useful for this project: https://www.aliexpress.us/item/3256804661575696.html.

**Comment by matgenois** [comment]
Is the PWM9685 considered an extension board or the main board in the output sections of the configuraiton tool?

**Comment by philipellisis** [comment]
That's correct, the main board on the PinOne does have one pwm9685 built into it. You could still use the 15 outputs that are tied to the data pins as outputs without a pwm9685 and will work just fine that way.
